# Generated by Django 4.2.7 on 2024-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"verbose_name_plural": "Experiences"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="postimages",
            options={"verbose_name_plural": "Post Images"},
        ),
        migrations.AlterModelOptions(
            name="posttag",
            options={"verbose_name_plural": "Post Tags"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "Tags"},
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="posttag",
            unique_together={("post", "tag")},
        ),
    ]
