# Generated by Django 4.2.7 on 2024-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_about_options_alter_experience_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimages",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
